### PR TITLE
JS async versions of the examples and tests

### PR DESCRIPTION
**Pull request by awlawl**

### CODE REVIEW

**Comment by yocontra** [comment]
Why have JS versions of the tests? CS compiles down to JS before it gets executed - it's the same thing

**Comment by yocontra** [comment]
btw your test is failing because the syntax is `q.Execute(function(arr) {`

**Comment by awlawl** [comment]
I wrote tests of the examples so that I was sure that the examples I put into the readme were working. You don't have to include them with the code if you don't want them. This was mainly for my certainty, but they might be useful for someone else to fiddle with. Your call.

The CS examples were not provided as tests, you could provide them in CS in place of my tests if you'd like.

Re Failing: I'm not sure what you mean. The tests are passing on my end. Are you saying that the syntax is not correct, pointing out what is incorrect? Line 49 and 72 match the syntax you describe. When I run "mocha examples.js", it tells me that 4 tests have completed.

Sorry if this is obvious, I am pretty new to node and very new to mocha.

**Comment by yocontra** [comment]
Oh I was looking at the commit "Async test not working, but checked in for now" but you fixed it in the next one

**Comment by yocontra** [comment]
Sorry I let this languish, I totally forgot about it. Thanks!

**Pull request merged**
